// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-42itit94rFIa90Cr812h6eIyVZ35WY',
    appId: '1:982254319426:web:982573b3873473ee7cfadb',
    messagingSenderId: '982254319426',
    projectId: 'ujikom-58d00',
    authDomain: 'ujikom-58d00.firebaseapp.com',
    storageBucket: 'ujikom-58d00.appspot.com',
    measurementId: 'G-QP9JM2Z6L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppuJ0lTg5kEOosrlulYxKqSxm3DmyS08',
    appId: '1:982254319426:android:01ea1ae4d75917387cfadb',
    messagingSenderId: '982254319426',
    projectId: 'ujikom-58d00',
    storageBucket: 'ujikom-58d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUu03y7ivHaMkgy8TStMELBr7grnOnZk',
    appId: '1:982254319426:ios:71e1857e9e1224d27cfadb',
    messagingSenderId: '982254319426',
    projectId: 'ujikom-58d00',
    storageBucket: 'ujikom-58d00.appspot.com',
    iosBundleId: 'com.example.ujikomtvanmuda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtUu03y7ivHaMkgy8TStMELBr7grnOnZk',
    appId: '1:982254319426:ios:71e1857e9e1224d27cfadb',
    messagingSenderId: '982254319426',
    projectId: 'ujikom-58d00',
    storageBucket: 'ujikom-58d00.appspot.com',
    iosBundleId: 'com.example.ujikomtvanmuda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2-42itit94rFIa90Cr812h6eIyVZ35WY',
    appId: '1:982254319426:web:6dee0828ffbc7acf7cfadb',
    messagingSenderId: '982254319426',
    projectId: 'ujikom-58d00',
    authDomain: 'ujikom-58d00.firebaseapp.com',
    storageBucket: 'ujikom-58d00.appspot.com',
    measurementId: 'G-DMCRQX27NL',
  );
}
